/*
 * This file is generated by jOOQ.
 */
package com.gitee.hengboy.micro.job.data.model.tables.records;


import com.gitee.hengboy.micro.job.data.model.tables.JobNodeInfo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 任务节点信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobNodeInfoRecord extends UpdatableRecordImpl<JobNodeInfoRecord> implements Record5<Integer, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = -1583199726;

    /**
     * Setter for <code>fission.job_node_info.JNI_ID</code>. 节点主键
     */
    public void setJniId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fission.job_node_info.JNI_ID</code>. 节点主键
     */
    public Integer getJniId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fission.job_node_info.JNI_ADDRESS</code>. 节点地址，格式为：IP:PORT，如：127.0.0.1:8080
     */
    public void setJniAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fission.job_node_info.JNI_ADDRESS</code>. 节点地址，格式为：IP:PORT，如：127.0.0.1:8080
     */
    public String getJniAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fission.job_node_info.JNI_LAST_HEART_TIME</code>. 最后一次心跳时间
     */
    public void setJniLastHeartTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>fission.job_node_info.JNI_LAST_HEART_TIME</code>. 最后一次心跳时间
     */
    public Timestamp getJniLastHeartTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>fission.job_node_info.JNI_CREATE_TIME</code>. 任务节点信息创建时间，第一次心跳时间
     */
    public void setJniCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>fission.job_node_info.JNI_CREATE_TIME</code>. 任务节点信息创建时间，第一次心跳时间
     */
    public Timestamp getJniCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>fission.job_node_info.JNI_MARK</code>. 备注信息
     */
    public void setJniMark(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fission.job_node_info.JNI_MARK</code>. 备注信息
     */
    public String getJniMark() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JobNodeInfo.JNI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JobNodeInfo.JNI_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return JobNodeInfo.JNI_LAST_HEART_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return JobNodeInfo.JNI_CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JobNodeInfo.JNI_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getJniId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getJniAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getJniLastHeartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getJniCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getJniMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getJniId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getJniAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getJniLastHeartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getJniCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getJniMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeInfoRecord value1(Integer value) {
        setJniId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeInfoRecord value2(String value) {
        setJniAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeInfoRecord value3(Timestamp value) {
        setJniLastHeartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeInfoRecord value4(Timestamp value) {
        setJniCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeInfoRecord value5(String value) {
        setJniMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeInfoRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobNodeInfoRecord
     */
    public JobNodeInfoRecord() {
        super(JobNodeInfo.JOB_NODE_INFO);
    }

    /**
     * Create a detached, initialised JobNodeInfoRecord
     */
    public JobNodeInfoRecord(Integer jniId, String jniAddress, Timestamp jniLastHeartTime, Timestamp jniCreateTime, String jniMark) {
        super(JobNodeInfo.JOB_NODE_INFO);

        set(0, jniId);
        set(1, jniAddress);
        set(2, jniLastHeartTime);
        set(3, jniCreateTime);
        set(4, jniMark);
    }
}
