/*
 * This file is generated by jOOQ.
 */
package com.gitee.hengboy.micro.job.data.model.tables.records;


import com.gitee.hengboy.micro.job.data.model.tables.JobNodeTriggerInfo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 节点任务信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobNodeTriggerInfoRecord extends UpdatableRecordImpl<JobNodeTriggerInfoRecord> implements Record9<Integer, String, String, String, String, Timestamp, Timestamp, String, String> {

    private static final long serialVersionUID = -1336960525;

    /**
     * Setter for <code>fission.job_node_trigger_info.NTI_ID</code>. 任务触发器主键
     */
    public void setNtiId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fission.job_node_trigger_info.NTI_ID</code>. 任务触发器主键
     */
    public Integer getNtiId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fission.job_node_trigger_info.NTI_KEY</code>. 任务触发器的key，用于标识唯一性
     */
    public void setNtiKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fission.job_node_trigger_info.NTI_KEY</code>. 任务触发器的key，用于标识唯一性
     */
    public String getNtiKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fission.job_node_trigger_info.NTI_LB_STRATEGY</code>. 负载均衡策略
     */
    public void setNtiLbStrategy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fission.job_node_trigger_info.NTI_LB_STRATEGY</code>. 负载均衡策略
     */
    public String getNtiLbStrategy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fission.job_node_trigger_info.NTI_CRON</code>. 任务触发器cron表达式
     */
    public void setNtiCron(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fission.job_node_trigger_info.NTI_CRON</code>. 任务触发器cron表达式
     */
    public String getNtiCron() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fission.job_node_trigger_info.NTI_NAME</code>. 任务触发器名称
     */
    public void setNtiName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fission.job_node_trigger_info.NTI_NAME</code>. 任务触发器名称
     */
    public String getNtiName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fission.job_node_trigger_info.NTI_CREATE_TIME</code>. 创建时间
     */
    public void setNtiCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>fission.job_node_trigger_info.NTI_CREATE_TIME</code>. 创建时间
     */
    public Timestamp getNtiCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>fission.job_node_trigger_info.NTI_START_TIME</code>. 启动时间
     */
    public void setNtiStartTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>fission.job_node_trigger_info.NTI_START_TIME</code>. 启动时间
     */
    public Timestamp getNtiStartTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>fission.job_node_trigger_info.NTI_JOB_CLASS</code>. 触发该任务的实现类全限定名
     */
    public void setNtiJobClass(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fission.job_node_trigger_info.NTI_JOB_CLASS</code>. 触发该任务的实现类全限定名
     */
    public String getNtiJobClass() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fission.job_node_trigger_info.NTI_MARK</code>. 备注信息
     */
    public void setNtiMark(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>fission.job_node_trigger_info.NTI_MARK</code>. 备注信息
     */
    public String getNtiMark() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, Timestamp, Timestamp, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, String, Timestamp, Timestamp, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JobNodeTriggerInfo.NTI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JobNodeTriggerInfo.NTI_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JobNodeTriggerInfo.NTI_LB_STRATEGY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JobNodeTriggerInfo.NTI_CRON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JobNodeTriggerInfo.NTI_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return JobNodeTriggerInfo.NTI_CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return JobNodeTriggerInfo.NTI_START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return JobNodeTriggerInfo.NTI_JOB_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return JobNodeTriggerInfo.NTI_MARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getNtiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNtiKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNtiLbStrategy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNtiCron();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNtiName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getNtiCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getNtiStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getNtiJobClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getNtiMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getNtiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNtiKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNtiLbStrategy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNtiCron();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNtiName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getNtiCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getNtiStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNtiJobClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getNtiMark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord value1(Integer value) {
        setNtiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord value2(String value) {
        setNtiKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord value3(String value) {
        setNtiLbStrategy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord value4(String value) {
        setNtiCron(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord value5(String value) {
        setNtiName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord value6(Timestamp value) {
        setNtiCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord value7(Timestamp value) {
        setNtiStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord value8(String value) {
        setNtiJobClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord value9(String value) {
        setNtiMark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobNodeTriggerInfoRecord values(Integer value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobNodeTriggerInfoRecord
     */
    public JobNodeTriggerInfoRecord() {
        super(JobNodeTriggerInfo.JOB_NODE_TRIGGER_INFO);
    }

    /**
     * Create a detached, initialised JobNodeTriggerInfoRecord
     */
    public JobNodeTriggerInfoRecord(Integer ntiId, String ntiKey, String ntiLbStrategy, String ntiCron, String ntiName, Timestamp ntiCreateTime, Timestamp ntiStartTime, String ntiJobClass, String ntiMark) {
        super(JobNodeTriggerInfo.JOB_NODE_TRIGGER_INFO);

        set(0, ntiId);
        set(1, ntiKey);
        set(2, ntiLbStrategy);
        set(3, ntiCron);
        set(4, ntiName);
        set(5, ntiCreateTime);
        set(6, ntiStartTime);
        set(7, ntiJobClass);
        set(8, ntiMark);
    }
}
