/*
 * This file is generated by jOOQ.
 */
package com.gitee.hengboy.micro.job.data.model;


import com.gitee.hengboy.micro.job.data.model.tables.JobNodeExecuteDetail;
import com.gitee.hengboy.micro.job.data.model.tables.JobNodeInfo;
import com.gitee.hengboy.micro.job.data.model.tables.JobNodeTriggerInfo;
import com.gitee.hengboy.micro.job.data.model.tables.records.JobNodeExecuteDetailRecord;
import com.gitee.hengboy.micro.job.data.model.tables.records.JobNodeInfoRecord;
import com.gitee.hengboy.micro.job.data.model.tables.records.JobNodeTriggerInfoRecord;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>fission</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<JobNodeExecuteDetailRecord, Integer> IDENTITY_JOB_NODE_EXECUTE_DETAIL = Identities0.IDENTITY_JOB_NODE_EXECUTE_DETAIL;
    public static final Identity<JobNodeInfoRecord, Integer> IDENTITY_JOB_NODE_INFO = Identities0.IDENTITY_JOB_NODE_INFO;
    public static final Identity<JobNodeTriggerInfoRecord, Integer> IDENTITY_JOB_NODE_TRIGGER_INFO = Identities0.IDENTITY_JOB_NODE_TRIGGER_INFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JobNodeExecuteDetailRecord> KEY_JOB_NODE_EXECUTE_DETAIL_PRIMARY = UniqueKeys0.KEY_JOB_NODE_EXECUTE_DETAIL_PRIMARY;
    public static final UniqueKey<JobNodeInfoRecord> KEY_JOB_NODE_INFO_PRIMARY = UniqueKeys0.KEY_JOB_NODE_INFO_PRIMARY;
    public static final UniqueKey<JobNodeTriggerInfoRecord> KEY_JOB_NODE_TRIGGER_INFO_PRIMARY = UniqueKeys0.KEY_JOB_NODE_TRIGGER_INFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<JobNodeExecuteDetailRecord, Integer> IDENTITY_JOB_NODE_EXECUTE_DETAIL = Internal.createIdentity(JobNodeExecuteDetail.JOB_NODE_EXECUTE_DETAIL, JobNodeExecuteDetail.NED_ID);
        public static Identity<JobNodeInfoRecord, Integer> IDENTITY_JOB_NODE_INFO = Internal.createIdentity(JobNodeInfo.JOB_NODE_INFO, JobNodeInfo.JNI_ID);
        public static Identity<JobNodeTriggerInfoRecord, Integer> IDENTITY_JOB_NODE_TRIGGER_INFO = Internal.createIdentity(JobNodeTriggerInfo.JOB_NODE_TRIGGER_INFO, JobNodeTriggerInfo.NTI_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<JobNodeExecuteDetailRecord> KEY_JOB_NODE_EXECUTE_DETAIL_PRIMARY = Internal.createUniqueKey(JobNodeExecuteDetail.JOB_NODE_EXECUTE_DETAIL, "KEY_job_node_execute_detail_PRIMARY", JobNodeExecuteDetail.NED_ID);
        public static final UniqueKey<JobNodeInfoRecord> KEY_JOB_NODE_INFO_PRIMARY = Internal.createUniqueKey(JobNodeInfo.JOB_NODE_INFO, "KEY_job_node_info_PRIMARY", JobNodeInfo.JNI_ID);
        public static final UniqueKey<JobNodeTriggerInfoRecord> KEY_JOB_NODE_TRIGGER_INFO_PRIMARY = Internal.createUniqueKey(JobNodeTriggerInfo.JOB_NODE_TRIGGER_INFO, "KEY_job_node_trigger_info_PRIMARY", JobNodeTriggerInfo.NTI_ID);
    }
}
