/*
 * This file is generated by jOOQ.
 */
package com.gitee.hengboy.micro.job.data.model.tables;


import com.gitee.hengboy.micro.job.data.model.Indexes;
import com.gitee.hengboy.micro.job.data.model.Keys;
import com.gitee.hengboy.micro.job.data.model.tables.records.JobNodeInfoRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 任务节点信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobNodeInfo extends TableImpl<JobNodeInfoRecord> {

    private static final long serialVersionUID = 362601682;

    /**
     * The reference instance of <code>fission.job_node_info</code>
     */
    public static final JobNodeInfo JOB_NODE_INFO = new JobNodeInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobNodeInfoRecord> getRecordType() {
        return JobNodeInfoRecord.class;
    }

    /**
     * The column <code>fission.job_node_info.JNI_ID</code>. 节点主键
     */
    public static final TableField<JobNodeInfoRecord, Integer> JNI_ID = createField("JNI_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), JOB_NODE_INFO, "节点主键");

    /**
     * The column <code>fission.job_node_info.JNI_ADDRESS</code>. 节点地址，格式为：IP:PORT，如：127.0.0.1:8080
     */
    public static final TableField<JobNodeInfoRecord, String> JNI_ADDRESS = createField("JNI_ADDRESS", org.jooq.impl.SQLDataType.VARCHAR(30), JOB_NODE_INFO, "节点地址，格式为：IP:PORT，如：127.0.0.1:8080");

    /**
     * The column <code>fission.job_node_info.JNI_LAST_HEART_TIME</code>. 最后一次心跳时间
     */
    public static final TableField<JobNodeInfoRecord, Timestamp> JNI_LAST_HEART_TIME = createField("JNI_LAST_HEART_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, JOB_NODE_INFO, "最后一次心跳时间");

    /**
     * The column <code>fission.job_node_info.JNI_CREATE_TIME</code>. 任务节点信息创建时间，第一次心跳时间
     */
    public static final TableField<JobNodeInfoRecord, Timestamp> JNI_CREATE_TIME = createField("JNI_CREATE_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, JOB_NODE_INFO, "任务节点信息创建时间，第一次心跳时间");

    /**
     * The column <code>fission.job_node_info.JNI_MARK</code>. 备注信息
     */
    public static final TableField<JobNodeInfoRecord, String> JNI_MARK = createField("JNI_MARK", org.jooq.impl.SQLDataType.VARCHAR(200), JOB_NODE_INFO, "备注信息");

    /**
     * No further instances allowed
     */
    private JobNodeInfo() {
        this(DSL.name("job_node_info"), null);
    }

    private JobNodeInfo(Name alias, Table<JobNodeInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private JobNodeInfo(Name alias, Table<JobNodeInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("任务节点信息"));
    }

    public <O extends Record> JobNodeInfo(Table<O> child, ForeignKey<O, JobNodeInfoRecord> key) {
        super(child, key, JOB_NODE_INFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.JOB_NODE_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<JobNodeInfoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_JOB_NODE_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JobNodeInfoRecord> getPrimaryKey() {
        return Keys.KEY_JOB_NODE_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JobNodeInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<JobNodeInfoRecord>>asList(Keys.KEY_JOB_NODE_INFO_PRIMARY);
    }
}
